import Head from 'next/head'
import Layout from '../components/Layout/Layout';
import React from 'react';
import fetchAPI from '../lib/api'
import Link from 'next/link';

export const AppContext = React.createContext();

export default function Home() {
  

  return (
      <>
        <Head>
          <title>jean Mazouni - Homepage</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.svg" />
        </Head>
        <div className='page-container'>
            <div>
            <h1>New portfolio coming soon</h1>
            <ul className='medias'>
              <li>
                <a href="https://twitter.com/Jean_mazouni">Twitter</a>
              </li>
              <li>
                <a href="https://www.linkedin.com/in/jean-mazouni-214803242/">Linkedin</a>
              </li>
              <li>
              <a href="https://www.instagram.com/jean_mazouni/">Instagram</a>
              </li>
            </ul>
            </div>
          </div>
        
      </>
  )
}


